name: Run Integration Tests from External Repository

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the primary repository (service code)
    - name: Checkout Service Repository
      uses: actions/checkout@v3

    # Build the service repository
    - name: Build Service
      run: |
        dotnet restore
        dotnet build --configuration Release

    # Start Docker (required for Testcontainers)
    - name: Start Docker
      run: sudo service docker start

    # Clone the integration test repository
    - name: Checkout IntegrationTest Repository
      uses: actions/checkout@v3
      with:
        repository: HobbyHub-Microservices/IntegrationTest
        path: integration-tests # Checkout into a subdirectory

    # Run the integration tests
    - name: Run xUnit Integration Tests
      working-directory: integration-tests
      run: dotnet test --configuration Release --logger:trx
      env:
        DOTNET_ENVIRONMENT: IntegrationTesting
        TESTCONTAINERS_HOST_OVERRIDE: "localhost"

    # Upload test results
    - name: Upload Test Results
      if: failure() || success()
      uses: actions/upload-artifact@v3
      with:
        name: integration-test-results
        path: integration-tests/**/TestResults/*.trx
