name: Run Integration Tests from External Repository

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the primary repository (service code)
    - name: Checkout Service Repository
      uses: actions/checkout@v3

    # Build the service repository
    - name: Build Service
      run: |
        dotnet restore
        dotnet build 

    # Start Docker (required for Testcontainers)
    - name: Start Docker
      run: sudo service docker start

    # Clone the integration test repository
    - name: Checkout IntegrationTest Repository
      uses: actions/checkout@v3
      with:
        repository: HobbyHub-Microservices/IntegrationTest

    # Run the integration tests
    - name: Run xUnit Integration Tests
      run: dotnet test 

