name: OWASP ZAP Scan

on:
  workflow_run:
    workflows: ["Docker Image CI"] # Triggers after the Docker Image CI workflow
    types:
      - completed

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Derive Docker image name dynamically from the repo name
    - name: Derive Docker image name
      run: |
        # Extract the repo name and convert it to lowercase
        REPO_NAME=$(basename "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="${{ secrets.DOCKER_USER }}/$REPO_NAME"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    # Step 3: Pull the Docker image
    - name: Pull Docker image
      run: |
        IMAGE_NAME=${{ env.IMAGE_NAME }}
        docker pull $IMAGE_NAME:latest

    # Step 4: Run the Docker container locally
    - name: Run the Docker container
      run: |
        IMAGE_NAME=${{ env.IMAGE_NAME }}
        docker run -d -p 8080:8080 --name app_container $IMAGE_NAME:latest

    # Step 5: Run OWASP ZAP Scan
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: 'http://localhost:8080' # Adjust the target URL if your app exposes a different port
        fail_on_warn: true
        rules_file: '.zap/rules.txt'
        report: true
        format: 'html'

    # Step 6: Stop and clean up the Docker container
    - name: Stop Docker container
      run: |
        docker stop app_container
        docker rm app_container

    # Step 7: Upload OWASP ZAP report as an artifact
    - name: Upload OWASP ZAP Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ZAP-Report
        path: owasp-zap-report.html
